import "server-only";
import { Octokit } from "@octokit/rest";
import { projectBuilderService } from "./project-builder.service";

export interface CreateRepoOptions {
  name: string;
  description?: string;
  isPrivate?: boolean;
}

export interface PushProjectOptions {
  projectId: string;
  repoName: string;
  accessToken: string;
  description?: string;
}

export interface GithubPushResult {
  success: boolean;
  repoUrl?: string;
  repoName?: string;
  error?: string;
}

class GitHubService {
  private getClient(accessToken: string): Octokit {
    return new Octokit({ auth: accessToken });
  }

  async getAuthenticatedUser(accessToken: string): Promise<{ login: string } | null> {
    try {
      const octokit = this.getClient(accessToken);
      const { data } = await octokit.rest.users.getAuthenticated();
      return { login: data.login };
    } catch {
      return null;
    }
  }

  async createRepo(
    accessToken: string,
    options: CreateRepoOptions
  ): Promise<{ repoUrl: string; fullName: string } | null> {
    try {
      const octokit = this.getClient(accessToken);
      const { data } = await octokit.rest.repos.createForAuthenticatedUser({
        name: options.name,
        description: options.description || "Generated by 0GPilot",
        private: options.isPrivate ?? false,
        auto_init: false,
      });
      return { repoUrl: data.html_url, fullName: data.full_name };
    } catch (err: unknown) {
      console.error("GitHub createRepo error:", err);
      return null;
    }
  }

  async pushProject(options: PushProjectOptions): Promise<GithubPushResult> {
    try {
      const octokit = this.getClient(options.accessToken);

      const user = await this.getAuthenticatedUser(options.accessToken);
      if (!user) {
        return { success: false, error: "Failed to fetch GitHub user" };
      }

      const safeRepoName = options.repoName
        .toLowerCase()
        .replace(/[^a-z0-9-]/g, "-")
        .replace(/-+/g, "-")
        .slice(0, 100);

      const created = await this.createRepo(options.accessToken, {
        name: safeRepoName,
        description: `Generated by 0GPilot — Project ${options.projectId}`,
        isPrivate: false,
      });

      if (!created) {
        return { success: false, error: "Failed to create GitHub repository" };
      }

      const files = await projectBuilderService.listFiles(options.projectId);

      const treeItems: Array<{
        path: string;
        mode: "100644";
        type: "blob";
        content: string;
      }> = [];

      for (const relativePath of files) {
        const content = await projectBuilderService.readFile(options.projectId, relativePath);
        if (content !== null) {
          treeItems.push({
            path: relativePath,
            mode: "100644",
            type: "blob",
            content,
          });
        }
      }

      if (treeItems.length === 0) {
        return { success: false, error: "No files found to commit" };
      }

      const { data: treeData } = await octokit.rest.git.createTree({
        owner: user.login,
        repo: safeRepoName,
        tree: treeItems,
      });

      const { data: commitData } = await octokit.rest.git.createCommit({
        owner: user.login,
        repo: safeRepoName,
        message: "feat: initial project generated by 0GPilot",
        tree: treeData.sha,
        parents: [],
      });

      await octokit.rest.git.createRef({
        owner: user.login,
        repo: safeRepoName,
        ref: "refs/heads/main",
        sha: commitData.sha,
      });

      return {
        success: true,
        repoUrl: created.repoUrl,
        repoName: created.fullName,
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : "GitHub push failed";
      console.error("GitHub pushProject error:", err);
      return { success: false, error: message };
    }
  }

  async repoExists(accessToken: string, owner: string, repo: string): Promise<boolean> {
    try {
      const octokit = this.getClient(accessToken);
      await octokit.rest.repos.get({ owner, repo });
      return true;
    } catch {
      return false;
    }
  }
}

export const githubService = new GitHubService();
