import { NextRequest, NextResponse } from "next/server";
import { verifySession, extractBearerToken } from "@/server/auth/session";
import { db } from "@/db";
import { githubService } from "@/services/github.service";
import { vercelService } from "@/services/vercel.service";

export const dynamic = "force-dynamic";

interface RouteContext {
  params: Promise<{ id: string }>;
}

export async function POST(req: NextRequest, context: RouteContext) {
  const { id } = await context.params;

  const token = extractBearerToken(req.headers.get("Authorization"));
  if (!token) {
    return NextResponse.json({ error: { code: "UNAUTHORIZED" } }, { status: 401 });
  }

  const session = await verifySession(token);
  if (!session) {
    return NextResponse.json({ error: { code: "INVALID_TOKEN" } }, { status: 401 });
  }

  const project = await db.project.findFirst({
    where: { id, userId: session.userId },
    select: {
      id: true,
      prompt: true,
      status: true,
      repoUrl: true,
      deploymentUrl: true,
    },
  });

  if (!project) {
    return NextResponse.json(
      { error: { code: "NOT_FOUND", message: "Project not found" } },
      { status: 404 }
    );
  }

  if (project.deploymentUrl) {
    return NextResponse.json({
      success: true,
      deploymentUrl: project.deploymentUrl,
      repoUrl: project.repoUrl,
      alreadyDeployed: true,
    });
  }

  const user = await db.user.findUnique({
    where: { id: session.userId },
    select: { githubToken: true, vercelToken: true, vercelTeamId: true },
  });

  if (!user?.githubToken) {
    return NextResponse.json(
      {
        error: {
          code: "GITHUB_NOT_CONNECTED",
          message: "Connect your GitHub account in Integrations before deploying.",
        },
      },
      { status: 400 }
    );
  }

  if (!user?.vercelToken) {
    return NextResponse.json(
      {
        error: {
          code: "VERCEL_NOT_CONNECTED",
          message: "Connect your Vercel account in Integrations before deploying.",
        },
      },
      { status: 400 }
    );
  }

  const repoName = project.prompt
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, "")
    .trim()
    .split(/\s+/)
    .slice(0, 4)
    .join("-")
    .concat(`-${id.slice(0, 6)}`);

  await db.project.update({
    where: { id },
    data: { status: "DEPLOYING" },
  });

  try {
    const pushResult = await githubService.pushProject({
      projectId: id,
      repoName,
      accessToken: user.githubToken,
      description: `Generated by 0GPilot: ${project.prompt.slice(0, 80)}`,
    });

    if (!pushResult.success || !pushResult.repoName) {
      await db.project.update({ where: { id }, data: { status: "FAILED" } });
      return NextResponse.json(
        { error: { code: "GITHUB_PUSH_FAILED", message: pushResult.error ?? "GitHub push failed" } },
        { status: 500 }
      );
    }

    await db.project.update({ where: { id }, data: { repoUrl: pushResult.repoUrl } });

    const deployResult = await vercelService.deployFromGitHub({
      repoFullName: pushResult.repoName,
      projectName: repoName,
      vercelToken: user.vercelToken,
      teamId: user.vercelTeamId ?? undefined,
    });

    if (!deployResult.success || !deployResult.deploymentUrl) {
      await db.project.update({ where: { id }, data: { status: "FAILED" } });
      return NextResponse.json(
        {
          error: {
            code: "VERCEL_DEPLOY_FAILED",
            message: deployResult.error ?? "Vercel deployment failed",
          },
          repoUrl: pushResult.repoUrl,
        },
        { status: 500 }
      );
    }

    await db.project.update({
      where: { id },
      data: {
        status: "DEPLOYED",
        deploymentUrl: deployResult.deploymentUrl,
        repoUrl: pushResult.repoUrl,
      },
    });

    return NextResponse.json({
      success: true,
      deploymentUrl: deployResult.deploymentUrl,
      repoUrl: pushResult.repoUrl,
    });
  } catch (err) {
    await db.project.update({ where: { id }, data: { status: "FAILED" } });
    const message = err instanceof Error ? err.message : "Deployment failed";
    return NextResponse.json(
      { error: { code: "DEPLOY_ERROR", message } },
      { status: 500 }
    );
  }
}
