import "server-only";
import { projectBuilderService } from "@/services/project-builder.service";
import { githubService } from "@/services/github.service";
import { db } from "@/db";
import { WorkflowState } from "../state";

export async function githubNode(
  state: WorkflowState
): Promise<Partial<WorkflowState>> {
  try {
    await projectBuilderService.build({
      projectId: state.projectId!,
      prompt: state.prompt,
      architecture: state.architecture,
      frontend: state.frontend,
      backend: state.backend,
      contracts: state.contracts,
      tests: state.tests,
    });

    if (state.error) {
      return { status: "GitHub Push Skipped (prior error)" };
    }

    const project = await db.project.findUnique({
      where: { id: state.projectId },
      include: { user: { select: { githubToken: true } } },
    });

    if (!project?.user.githubToken) {
      return { status: "GitHub Push Skipped (no token)" };
    }

    const repoName = state.prompt
      .toLowerCase()
      .replace(/[^a-z0-9\s]/g, "")
      .trim()
      .split(/\s+/)
      .slice(0, 4)
      .join("-")
      .concat(`-${state.projectId!.slice(0, 8)}`);

    const pushResult = await githubService.pushProject({
      projectId: state.projectId!,
      repoName,
      accessToken: project.user.githubToken,
      description: `Generated by 0GPilot: ${state.prompt.slice(0, 100)}`,
    });

    if (!pushResult.success) {
      return {
        error: pushResult.error || "GitHub push failed",
        status: "GitHub Push Failed",
      };
    }

    await db.project.update({
      where: { id: state.projectId },
      data: {
        repoUrl: pushResult.repoUrl,
        repoName: pushResult.repoName,
      },
    });

    return {
      status: `GitHub Pushed — ${pushResult.repoUrl}`,
    };
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "GitHub node failed";
    console.error(message);
    return { error: message, status: "FAILED" };
  }
}
